# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# Minor change
on:
  pull_request:
    branches:
      - main
      - dev
  push:

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Environment Variables"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "\n\n"
          echo "Contexts"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
