# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches:
      - main
      - dev
  push:

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_BASE_REF: ${{ github.base_ref }}
      GITHUB_REF: ${{ github.ref }}
    steps:
      - name: Echo
        run: |
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_REF: $GITHUB_REF"
